# Generated by Django 3.2.23 on 2023-11-11 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=17, null=True)),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.CharField(choices=[('8:00', '8:00'), ('8:30', '8:30'), ('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00')], default='8:00', max_length=5)),
                ('tables_booked', models.IntegerField(choices=[(0, 'Single window seat'), (1, 'Small- 2 seats'), (2, 'Medium- 4 seats'), (3, 'Large- 6 seats')], default=0)),
                ('additional_info', models.TextField(blank=True, max_length=400, null=True)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.IntegerField(choices=[(0, 'Awaiting confirmation'), (1, 'Booking confirmed'), (2, 'Booking declined')], default=0)),
                ('booking_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.customer')),
            ],
            options={
                'ordering': ['booked_on'],
            },
        ),
    ]
