# Generated by Django 3.2.23 on 2023-11-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.IntegerField(choices=[(0, '8:00 - 8:30'), (1, '8:30 - 9:00'), (2, '9:00 - 9:30'), (3, '9:30 - 10:00'), (4, '10:00 - 10:30'), (5, '10:30 - 11:00'), (6, '11:00 - 11:30'), (7, '11:30 - 12:00'), (8, '12:00 - 12:30'), (9, '12:30 - 13:00'), (10, '13:00 - 13:30'), (11, '13:30 - 14:00'), (12, '14:00 - 14:30'), (13, '14:30 - 15:00'), (17, '15:00 - 15:30'), (18, '15:30 - 16:00'), (19, '16:00 - 16:30'), (20, '16:30 - 17:00')], default='8:00'),
        ),
    ]
