# Generated by Django 4.2.7 on 2023-11-29 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='customer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(choices=[('0', '8:00 - 8:30'), ('1', '8:30 - 9:00'), ('2', '9:00 - 9:30'), ('3', '9:30 - 10:00'), ('4', '10:00 - 10:30'), ('5', '10:30 - 11:00'), ('6', '11:00 - 11:30'), ('7', '11:30 - 12:00'), ('8', '12:00 - 12:30'), ('9', '12:30 - 13:00'), ('10', '13:00 - 13:30'), ('11', '13:30 - 14:00'), ('12', '14:00 - 14:30'), ('13', '14:30 - 15:00'), ('17', '15:00 - 15:30'), ('18', '15:30 - 16:00'), ('19', '16:00 - 16:30'), ('20', '16:30 - 17:00')], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_confirmed',
            field=models.CharField(choices=[('0', 'Awaiting confirmation'), ('1', 'Booking confirmed'), ('2', 'Booking declined')], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tables_booked',
            field=models.CharField(choices=[('1', 'Single window seat'), ('2', 'Small- 2 seats'), ('4', 'Medium- 4 seats'), ('6', 'Large- 6 seats')], default='1', max_length=50),
        ),
    ]
