# Generated by Django 4.2.7 on 2023-11-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_tables_booked_booking_table_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_confirmed',
            field=models.CharField(choices=[('Awaiting confirmation', 'Awaiting confirmation'), ('Booking confirmed', 'Booking confirmed'), ('Booking declined', 'Booking declined')], default='Awaiting confirmation', max_length=50),
        ),
    ]
